#Inventory Connector Range
#Range: 4 ~ 256
inventoryConnectorRange = 32
#Only Allow Trims to Connect Inventories
onlyTrimsConnect = false
#Inventory Cable Connector Maximum number of cables
#Range: > 16
invCableConnectorMaxScanSize = 3074
#Wireless terminal reach
#Range: 4 ~ 64
wirelessReach = 32
#Multiblock inventories
multiblockInv = []
#Wireless terminal reach
#Range: 16 ~ 512
advWirelessRange = 128

